/* AUTH */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ADD_MEMBER_SUCCESS = "AUTH_ADD_MEMBER_SUCCESS";
export const AUTH_ADD_MEMBER_FAILURE = "AUTH_ADD_MEMBER_FAILURE";

/* Admin */
export const ADMIN_GET_MEMBER_LIST = "ADMIN_GET_MEMBER_LIST";
export const ADMIN_GET_MEMBER_SUCCESS = "ADMIN_GET_MEMBER_SUCCESS";
export const ADMIN_GET_MEMBER_FAILURE = "ADMIN_GET_MEMBER_FAILURE";


/* Book */
export const BOOK_SEARCH_EXTERNAL_API = "BOOK_SEARCH_EXTERNAL_API";
export const BOOK_SEARCH_EXTERNAL_API_SUCCESS = "BOOK_SEARCH_EXTERNAL_API_SUCCESS";
export const BOOK_SEARCH_EXTERNAL_API_FAILURE = "BOOK_SEARCH_EXTERNAL_API_FAILURE";
export const BOOK_SEARCH = "BOOK_SEARCH";
export const BOOK_SEARCH_SUCCESS = "BOOK_SEARCH_SUCCESS";
export const BOOK_SEARCH_FAILURE = "BOOK_SEARCH_FAILURE";
export const BOOK_REGISTER_BOOK_SELECT = "BOOK_REGISTER_BOOK_SELECT";
export const BOOK_REGISTER = "BOOK_REGISTER";
export const BOOK_REGISTER_SUCCESS = "BOOK_REGISTER_SUCCESS";
export const BOOK_REGISTER_FAILURE = "BOOK_REGISTER_FAILURE";
