/* AUTH */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* Admin */
export const ADMIN_GET_MEMBER_LIST = "ADMIN_GET_MEMBER_LIST";
export const ADMIN_GET_MEMBER_SUCCESS = "ADMIN_GET_MEMBER_SUCCESS";
export const ADMIN_GET_MEMBER_FAILURE = "ADMIN_GET_MEMBER_FAILURE";
